apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: default-pipeline
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: default-pipeline
    app.kubernetes.io/part-of: devfile-sample-go-basic
  name: default-pipeline
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: default-pipeline
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: default-pipeline
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/vigneshsri-tenant/devfile-sample-go-basic/default-pipeline@sha256:3f691b87837218f2d78686685fefa62d7a5b50747a513e388636d745687ed56e
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
