apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: default-pipeline
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: default-pipeline
    app.kubernetes.io/part-of: devfile-sample-go-basic
  name: default-pipelineuuuk
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: default-pipeline
    weight: null
status: {}
